img_dir: "data"
mask_dir: "data"

train_dl_args:
  batch_size: 4
  shuffle: True
  num_workers: 4
  pin_memory: True

# model architecture
model:
  type: architecture.ModelArchitecture

# pytorch-lightning trainer config
trainer:
  type: pytorch_lightning.Trainer
  gpus: 0
  max_epochs: 10
  log_every_n_steps: 100
  num_sanity_val_steps: 2
  logger: True

# checkpoint callback
checkpoint:
  type: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: "./dir_for_checkpoints"
  filename: "{epoch}-{some_validation_metric:.5f}"
  monitor: some_validation_metric
  verbose: True
  mode: max
  save_top_k: 2

# logger callback
logger:
  type: pytorch_lightning.loggers.CSVLogger
  save_dir: logs
  name: best_logs

# optimizer
optimizer:
  type: torch.optim.Adam
  lr: 0.001

# scheduler for optimizer
scheduler:
  lr_scheduler:
    type: torch.optim.lr_scheduler.ReduceLROnPlateau
    mode: min
    factor: 0.094
    patience: 3
    cooldown: 1
    verbose: True
  lr_dict:
    interval: epoch
    frequency: 1
    monitor: train_loss


# transforms and augmentations
# (thanks to albumentations.core.serialization.from_dict function, transforms can be serialized)
train_augs:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    transforms:
      - __class_fullname__: albumentations.augmentations.geometric.resize.Resize
        height: 1024
        width: 1024
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        mean:
          - 0.0
          - 0.0
          - 0.0
        std:
          - 1.0
          - 1.0
          - 1.0
      - __class_fullname__: albumentations.pytorch.transforms.ToTensorV2


val_augs:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    transforms:
      - __class_fullname__: albumentations.augmentations.geometric.resize.Resize
        height: 1024
        width: 1024
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        mean:
          - 0.0
          - 0.0
          - 0.0
        std:
          - 1.0
          - 1.0
          - 1.0
      - __class_fullname__: albumentations.pytorch.transforms.ToTensorV2
